# Generated by Django 5.1.15 on 2026-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_proficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_year']},
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_attended',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Field / Major'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.CharField(default=2023, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=200, verbose_name='School / University'),
        ),
    ]
