# Generated by Django 6.0.3 on 2026-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a screenshot or preview image for this project', null=True, upload_to='projects/'),
        ),
    ]
